package main

import (
	"fmt"
	"github.com/gin-gonic/gin"
	"github.com/mailjet/mailjet-apiv3-go"
	"log"
	"net/http"
	"os"
)

func sendMailHandler(c *gin.Context) {
	mailjetClient := mailjet.NewMailjetClient("d4f64bc764c4576540cf8033fd69a1e5", "624fbd6d20aad779ca3db090baa0294a")
	messagesInfo := []mailjet.InfoMessagesV31{
		mailjet.InfoMessagesV31{
			From: &mailjet.RecipientV31{
				Email: "yaronp@gmail.com",
				Name:  "yaron",
			},
			To: &mailjet.RecipientsV31{
				mailjet.RecipientV31{
					Email: "yaronp@gmail.com",
					Name:  "yaron",
				},
			},
			Subject:  "Hello lusha!",
			TextPart: "This mail is generated by lusha test. https://jan20.lushatest.com, Cheers, Yaron ",
			HTMLPart: `Hi Arik,
    <br>
    This mail is generated by lusha test. https://jan20.lushatest.com
    <br>
    Cheers, Yaron.`,
			CustomID: "AppGettingStartedTest",
		},
	}
	messages := mailjet.MessagesV31{Info: messagesInfo}
	res, err := mailjetClient.SendMailV31(&messages)

	if err != nil {
		c.String(http.StatusInternalServerError, err.Error())
		log.Fatal(err)
	} else {
		fmt.Printf("SendMail message send data: %+v\n", res)
		c.JSON(200, res)
	}
}

func main() {
	port := os.Getenv("PORT")
	if port == "" {
		port = "5000"
	}

	r := gin.Default()
	r.GET("/ping", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"message": "pong",
		})
	})

	r.GET("/", func(c *gin.Context) { c.File("public/index.html") })
	r.POST("/send", sendMailHandler)

	r.Run(":" + port)

}
