const express = require('express')
const nodemailer = require("nodemailer")
const {response} = require("express");

// https://www.youtube.com/watch?v=b0g-FJ5Zbb8

const app = express()
const port = 3000

const mainPage = `
<HTML>
    <H1>Hello Lusha</H1>
    <form action="/send" method="post">
        <input type="submit">
    </form>
</HTML>`

const responsePage = `
<HTML>
<h1>Status code: 42</h1>
<h2>Thank you for spamming us!</h2>
 <img width="512" alt="Don&#039;t Panic" src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Don%27t_Panic.svg/512px-Don%27t_Panic.svg.png">
</HTML>
`;

const message = {
    from: "yaronp@gmail.com",
    to: "yaronp@gmail.com",
    subject: "Hello lusha!",
    text: "",
    html: `Hi Arik,
    <br>
    This mail is generated by lusha test. https://jan20.lushatest.com
    <br>
    Cheers, Yaron.`
};

app.get('/', (req, res) => {
    res.send(mainPage)
})

app.post('/send', async (req, res) => {
    const transport = nodemailer.createTransport({
        host: "email-smtp.eu-central-1.amazonaws.com",
        port: 465,
        secure: true,
        auth: {
            user: "AKIA5BW7S6ZFLC4Y6XJ5",
            pass: "BI7W801yR5TFgtrVb3eG0DjE9/AYtUwgJTE+PgZjDyY7"
        }
    });

    // https://nodemailer.com/message/

    // await transport.sendMail(message)

    res.send(responsePage)
})

app.listen(port, () => {
    console.log(`Example app listening on port ${port}`)
})